title: PUSH2AIM landing page
email: j.eisenlohr@push2aim.com
description: Motivational Fitness Friend you can chat with. Be part of HeyBuddy's public beta!
baseurl:
url: https://push2aim.github.io
twitter_username: push2aim
github_username:  Push2Aim

# Facebook SDK Settings
facebook_sdk:
  app_id: 640247136178069
  page_id: 1808838016021226
  data-ref: FROM_LANDING_PAGE
  color: blue
  size: xlarge

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
